# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import _thread

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QIcon, QPalette, QBrush, QPixmap
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QFileDialog, QAction


class Ui_AboutWindow(QMainWindow):
    controlSignal = pyqtSignal(str,str)
    def set_version(self):
        one_talk = ""
        try:
            one_talk = '一言:' +  requests.get('https://v1.hitokoto.cn/?encode=text').text
        except:
            pass
        while True:
            self.statusbar.showMessage("当前版本: V1.0     " + one_talk,2147483647)
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(578, 361)
        self.centralwidget = QtWidgets.QWidget(AboutWindow)
        self.centralwidget.setObjectName("centralwidget")
        AboutWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AboutWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        AboutWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AboutWindow)
        self.statusbar.setObjectName("statusbar")
        AboutWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(AboutWindow)
        self.toolBar.setObjectName("toolBar")
        AboutWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        showAction = QAction(QIcon("./images/vipcenter_icon.png"), "show", self)
        showAction.setText("打开主界面")
        showAction.triggered.connect(self.show_main)

        playAction = QAction(QIcon("./images/play_button.png"), "play", self)
        playAction.setText("播放/暂停")
        playAction.triggered.connect(self.play)

        closeAction = QAction(QIcon("./images/logout_icon.png"), "play", self)
        closeAction.setText("退出本程序")
        closeAction.triggered.connect(self.quit_main)

        aboutAction = QAction(QIcon("./images/login.ico"), "new", self)
        aboutAction.setText("关于")
        aboutAction.triggered.connect(self.about)

        self.toolBar.setToolButtonStyle(3)
        self.toolBar.addAction(showAction)
        self.toolBar.addAction(playAction)
        self.toolBar.addAction(closeAction)
        self.toolBar.addAction(aboutAction)
        self.action = QtWidgets.QAction(AboutWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/login.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(AboutWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/images/play_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon1)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(AboutWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/images/last_song.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_3.setIcon(icon2)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(AboutWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/images/next_song.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_4.setIcon(icon3)
        self.action_4.setObjectName("action_4")
        self.action_OneMusic = QtWidgets.QAction(AboutWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/images/vipcenter_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OneMusic.setIcon(icon4)
        self.action_OneMusic.setObjectName("action_OneMusic")
        self.action_OneMusic_2 = QtWidgets.QAction(AboutWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/images/logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OneMusic_2.setIcon(icon5)
        self.action_OneMusic_2.setObjectName("action_OneMusic_2")
        self.action_7 = QtWidgets.QAction(AboutWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/images/connect_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_7.setIcon(icon6)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()
        self.menu.addAction(self.action_OneMusic)
        self.menu.addAction(self.action_OneMusic_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_7)
        self.menu_2.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.action.triggered.connect(self.about)
        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)
        self.statusbar.showMessage("当前版本: V1.0",2147483647)
        self.action_2.triggered.connect(self.play)
        self.action_3.triggered.connect(self.last)
        self.action_4.triggered.connect(self.next)
        self.action_OneMusic.triggered.connect(self.show_main)
        self.action_OneMusic_2.triggered.connect(self.quit_main)
        self.action_7.triggered.connect(self.fromlocal)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("./images/bg.jpg")))
        self.setPalette(palette)
        _thread.start_new_thread(self.set_version,())

    def last(self):
        self.controlSignal.emit("last",'')
    def next(self):
        self.controlSignal.emit("next",'')
    def show_main(self):
        self.controlSignal.emit("show",'')
    def quit_main(self):
        self.controlSignal.emit("quit",'')
    def play(self):
        self.controlSignal.emit("play",'')
    def fromlocal(self):
        path = QFileDialog.getOpenFileName(self,'选择MP3:', filter="音乐(*.MP3)")
        if path[0] != '':
            self.controlSignal.emit("playlocal",path[0])

    def about(self):
        QMessageBox.information(self,"Tips:","OneMusic是一个第三方网易云音乐平台\n目前已实现:\n  1.音乐搜索\n  2.音乐播放\n  3.实时歌词同步\n  4.首页热门歌单推荐\n  5.可登陆网易云账号\n  6.正常进行账号签到")
    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "关于"))
        self.menu.setTitle(_translate("AboutWindow", "主菜单"))
        self.menu_2.setTitle(_translate("AboutWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("AboutWindow", "toolBar"))
        self.action.setText(_translate("AboutWindow", "关于"))
        self.action_2.setText(_translate("AboutWindow", "播放/暂停"))
        self.action_3.setText(_translate("AboutWindow", "播放上一首"))
        self.action_4.setText(_translate("AboutWindow", "播放下一首"))
        self.action_OneMusic.setText(_translate("AboutWindow", "打开OneMusic"))
        self.action_OneMusic_2.setText(_translate("AboutWindow", "退出OneMusic"))
        self.action_7.setText(_translate("AboutWindow", "从电脑中选择播放..."))
import about_rc
if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow

    app = QApplication(sys.argv)
    w = Ui_AboutWindow()
    w.setupUi(w)
    w.show()
    sys.exit(app.exec_())