# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_UserInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser as web

from PyQt5.QtCore import pyqtSignal
from NetEase import apis


class Ui_Dialog(object):

    logoutSignal = pyqtSignal(bool)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 458)
        Dialog.setStyleSheet("#Dialog {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"#widget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"#closeButton {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#closeButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(232, 16, 16);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("border-radius:7px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 50, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(129, 50, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(210, 50, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);")
        self.label_3.setObjectName("label_3")
        self.label_news = QtWidgets.QLabel(self.widget)
        self.label_news.setGeometry(QtCore.QRect(42, 29, 41, 21))
        self.label_news.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label_news.setAlignment(QtCore.Qt.AlignCenter)
        self.label_news.setObjectName("label_news")
        self.label_follow = QtWidgets.QLabel(self.widget)
        self.label_follow.setGeometry(QtCore.QRect(120, 29, 41, 21))
        self.label_follow.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label_follow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_follow.setObjectName("label_follow")
        self.label_followers = QtWidgets.QLabel(self.widget)
        self.label_followers.setGeometry(QtCore.QRect(201, 29, 41, 21))
        self.label_followers.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label_followers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_followers.setObjectName("label_followers")
        self.button_sign = QtWidgets.QPushButton(self.widget)
        self.button_sign.setGeometry(QtCore.QRect(100, 90, 81, 31))
        self.button_sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_sign.setStyleSheet("QPushButton#button_sign{\n"
"border-radius:15px;\n"
"color: rgb(51, 51, 51);\n"
"font: 11pt \"微软雅黑\";\n"
"border:1px solid;\n"
"border-color: rgb(216, 216, 216);\n"
"qproperty-icon: url(:/pic/images/signicon.png) off, url(:/pic/images/signicon.png) on;\n"
"}\n"
"QPushButton#button_sign:hover{\n"
"background-color: rgb(243, 243, 243);\n"
"}")
        self.button_sign.setObjectName("button_sign")
        self.label_line = QtWidgets.QLabel(self.widget)
        self.label_line.setGeometry(QtCore.QRect(0, 140, 281, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_line.setFont(font)
        self.label_line.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);\n"
"border:1px solid;\n"
"border-color: rgb(237, 237, 237);")
        self.label_line.setText("")
        self.label_line.setObjectName("label_line")
        self.button_vipcenter = QtWidgets.QPushButton(self.widget)
        self.button_vipcenter.setGeometry(QtCore.QRect(0, 150, 281, 38))
        self.button_vipcenter.setStyleSheet("QPushButton#button_vipcenter{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/vipcenter_icon.png) off, url(:/pic/images/vipcenter_icon.png) on;\n"
"}\n"
"QPushButton#button_vipcenter:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_vipcenter.setObjectName("button_vipcenter")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(260, 157, 16, 20))
        self.label_4.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.button_grade = QtWidgets.QPushButton(self.widget)
        self.button_grade.setGeometry(QtCore.QRect(0, 190, 281, 38))
        self.button_grade.setStyleSheet("QPushButton#button_grade{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/grade_icon.png) off, url(:/pic/images/grade_icon.png) on;\n"
"}\n"
"QPushButton#button_grade:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_grade.setObjectName("button_grade")
        self.button_mall = QtWidgets.QPushButton(self.widget)
        self.button_mall.setGeometry(QtCore.QRect(0, 230, 281, 38))
        self.button_mall.setStyleSheet("QPushButton#button_mall{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/mall_icon.png) off, url(:/pic/images/mall_icon.png) on;\n"
"}\n"
"QPushButton#button_mall:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_mall.setObjectName("button_mall")
        self.label_line_2 = QtWidgets.QLabel(self.widget)
        self.label_line_2.setGeometry(QtCore.QRect(0, 277, 281, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_line_2.setFont(font)
        self.label_line_2.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);\n"
"border:1px solid;\n"
"border-color: rgb(237, 237, 237);")
        self.label_line_2.setText("")
        self.label_line_2.setObjectName("label_line_2")
        self.button_info = QtWidgets.QPushButton(self.widget)
        self.button_info.setGeometry(QtCore.QRect(0, 290, 281, 38))
        self.button_info.setStyleSheet("QPushButton#button_info{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/info_icon.png) off, url(:/pic/images/info_icon.png) on;\n"
"}\n"
"QPushButton#button_info:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_info.setObjectName("button_info")
        self.button_connect = QtWidgets.QPushButton(self.widget)
        self.button_connect.setGeometry(QtCore.QRect(0, 330, 281, 38))
        self.button_connect.setStyleSheet("QPushButton#button_connect{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/connect_icon.png) off, url(:/pic/images/connect_icon.png) on;\n"
"}\n"
"QPushButton#button_connect:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_connect.setObjectName("button_connect")
        self.label_line_3 = QtWidgets.QLabel(self.widget)
        self.label_line_3.setGeometry(QtCore.QRect(0, 380, 281, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_line_3.setFont(font)
        self.label_line_3.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(103, 103, 103);\n"
"border:1px solid;\n"
"border-color: rgb(237, 237, 237);")
        self.label_line_3.setText("")
        self.label_line_3.setObjectName("label_line_3")
        self.button_logout = QtWidgets.QPushButton(self.widget)
        self.button_logout.setGeometry(QtCore.QRect(0, 390, 281, 38))
        self.button_logout.setStyleSheet("QPushButton#button_logout{\n"
"border-radius:0px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(51, 51, 51);\n"
"qproperty-icon: url(:/pic/images/logout_icon.png) off, url(:/pic/images/logout_icon.png) on;\n"
"}\n"
"QPushButton#button_logout:hover{\n"
"background-color: rgb(240, 241, 242);\n"
"}")
        self.button_logout.setObjectName("button_logout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(260, 199, 16, 20))
        self.label_5.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(260, 239, 16, 20))
        self.label_6.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(260, 299, 16, 20))
        self.label_7.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(260, 338, 16, 20))
        self.label_8.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.widget)
        self.button_grade.clicked.connect(self.click_level)
        self.button_info.clicked.connect(self.click_info)
        self.button_mall.clicked.connect(self.click_mall)
        self.button_connect.clicked.connect(self.click_connect)
        self.button_vipcenter.clicked.connect(self.click_vip)
        self.button_logout.clicked.connect(self.click_logout)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.button_sign.clicked.connect(self.sign_in)

    def sign_in(self):
        res = apis.user.SetSignin()
        if res['code'] == -2:
            self.button_sign.setText('重复签到')
            self.button_sign.setGeometry(self.button_sign.geometry().top(),
                                         self.button_sign.geometry().left()-10,
                                         self.button_sign.geometry().width() + 20,
                                         self.button_sign.geometry().height())
            self.button_sign.setStyleSheet("QPushButton#button_sign{\n"
                                           "border-radius:15px;\n"
                                           "color: rgb(201, 201, 201);\n"
                                           "font: 11pt \"微软雅黑\";\n"
                                           "border:1px solid;\n"
                                           "border-color: rgb(216, 216, 216);\n"
                                           "background-color: rgb(243, 243, 243);"
                                           "qproperty-icon: url(:/pic/images/signicon.png) off, url(:/pic/images/signicon.png) on;\n"
                                           "}\n")
            self.button_sign.setEnabled(False)
        else:
            self.button_sign.setText('签到成功~')
            self.button_sign.setGeometry(self.button_sign.geometry().top(),
                                         self.button_sign.geometry().left() - 10,
                                         self.button_sign.geometry().width() + 20,
                                         self.button_sign.geometry().height())
            self.button_sign.setStyleSheet("QPushButton#button_sign{\n"
                                           "border-radius:15px;\n"
                                           "color: rgb(201, 201, 201);\n"
                                           "font: 11pt \"微软雅黑\";\n"
                                           "border:1px solid;\n"
                                           "border-color: rgb(216, 216, 216);\n"
                                           "background-color: rgb(243, 243, 243);"
                                           "qproperty-icon: url(:/pic/images/signicon.png) off, url(:/pic/images/signicon.png) on;\n"
                                           "}\n")
            self.button_sign.setEnabled(False)

    def click_logout(self):
        self.logoutSignal.emit(True)
    def click_vip(self):
        web.open_new('https://music.163.com/#/member')
        self.close()
    def click_level(self):
        web.open_new('https://music.163.com/#/user/level')
        self.close()
    def click_mall(self):
        web.open_new('https://music.163.com/store/product')
        self.close()
    def click_info(self):
        web.open_new('https://music.163.com/#/user/update')
        self.close()
    def click_connect(self):
        web.open_new('https://music.163.com/#/user/binding/m/list')
        self.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "动态"))
        self.label_2.setText(_translate("Dialog", "关注"))
        self.label_3.setText(_translate("Dialog", "粉丝"))
        self.label_news.setText(_translate("Dialog", "0"))
        self.label_follow.setText(_translate("Dialog", "0"))
        self.label_followers.setText(_translate("Dialog", "0"))
        self.button_sign.setText(_translate("Dialog", "签到"))
        self.button_vipcenter.setText(_translate("Dialog", "会员中心                                      "))
        self.label_4.setText(_translate("Dialog", ">"))
        self.button_grade.setText(_translate("Dialog", "等级                                             "))
        self.button_mall.setText(_translate("Dialog", "商城                                             "))
        self.button_info.setText(_translate("Dialog", "个人信息设置                                "))
        self.button_connect.setText(_translate("Dialog", "绑定社交账号                                "))
        self.button_logout.setText(_translate("Dialog", "退出登录                                      "))
        self.label_5.setText(_translate("Dialog", ">"))
        self.label_6.setText(_translate("Dialog", ">"))
        self.label_7.setText(_translate("Dialog", ">"))
        self.label_8.setText(_translate("Dialog", ">"))
import info_rc
